FlowRate:
  MillisecondsPerMilliliter: 117

FillDurationMs: 3000
CleanDurationMs: 10000

LiquidAssignments:
  - "Aperol"
  - "Prosecco"
  - ""
  - ""
  - "Gin"
  - "Tonic"
  - ""
  - ""
  - ""
  - ""

Modes:
  - Name: "Gin Mode"
    Color: "#559CAD"
    LedColor: "CYAN"
    LiquidAssignments:
      - "Gin"
      - "Tonic"
      - "Lemon"
      - ""
  - Name: "Vodka Mode"
    Color: "#F7940A"
    LedColor: "CYAN"
    LiquidAssignments:
      - "Vodka"
      - "Tonic"
      - "Lemon"
      - ""
  - Name: "OG Mode"
    Color: "#F46036"
    LedColor: "RED"
    LiquidAssignments:
      - "Campari"
      - "Vermouth"
      - ""
      - "Gin"
