<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.8"/>
        <PackageReference Include="Avalonia.Desktop" Version="11.3.8"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.8"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.8"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.8">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="System.IO.Ports" Version="10.0.1" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Assets\logo.png" />
      <AvaloniaResource Include="Assets\logo.png" />
      <None Remove="Assets\logo-white.png" />
      <None Remove="Assets\logo_white.png" />
      <AvaloniaResource Include="Assets\logo_white.png" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="ProductsPage.axaml.cs">
        <DependentUpon>ProductsPage.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\SplashPage.axaml.cs">
        <DependentUpon>SplashPage.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\CocktailsMenu.axaml.cs">
        <DependentUpon>CocktailsMenu.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\ContainerSetupPage.axaml.cs">
        <DependentUpon>ContainerSetupPage.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>
</Project>
