<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.8"/>
        <PackageReference Include="Avalonia.Desktop" Version="11.3.8"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.8"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.8"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.8">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="System.IO.Ports" Version="10.0.1" />
        <PackageReference Include="YamlDotNet" Version="16.1.2" />
    </ItemGroup>

    <ItemGroup>
      <AvaloniaResource Include="Assets\logo_white.png" />
      <AvaloniaResource Include="Assets\americano.png" />
      <AvaloniaResource Include="Assets\ginlemon.png" />
      <AvaloniaResource Include="Assets\gintonic.png" />
      <AvaloniaResource Include="Assets\negroni.png" />
      <AvaloniaResource Include="Assets\negronisbagliato.png" />
      <AvaloniaResource Include="Assets\vodkalemon.png" />
      <AvaloniaResource Include="Assets\vodkaredbull.png" />
      <AvaloniaResource Include="Assets\vodkatonic.png" />
      <AvaloniaResource Include="Assets\DaevaMaxFinal.png" />
      <AvaloniaResource Include="Assets\gear.svg" />
      <AvaloniaResource Include="Assets\DaevaDark.png" />
      <AvaloniaResource Include="Assets\camparispritz.png" />
      <AvaloniaResource Include="Assets\DaevaMiniLogo.png" />
      <AvaloniaResource Include="Assets\DaevaWhite.png" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="appsettings.yaml">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="ProductsPage.axaml.cs">
        <DependentUpon>ProductsPage.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\Max\SplashPage.axaml.cs">
        <DependentUpon>SplashPage.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Max\ContainerSetupPage.axaml.cs">
        <DependentUpon>ContainerSetupPage.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Max\CocktailMenu.axaml.cs">
        <DependentUpon>CocktailMenu.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Controls\CocktailCard.axaml.cs">
        <DependentUpon>CocktailCard.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>
</Project>
