FlowRate:
  MillisecondsPerMilliliter: 60

FillDurationMs: 3000
CleanDurationMs: 10000

Modes:
  - Name: "Gin Mode"
    Color: "#559CAD"
    LedColor: "CYAN"
    LiquidAssignments:
      - "Gin"
      - "Tonic"
      - "Limone"
      - ""
    Cocktails:
      - Id: "gintonic"
        Name: "Gin Tonic"
        Subtitle: "Gin, Tonica"
        Image: "gintonic"
        Theme: "Teal"
        IsActive: true
        LedR: 255
        LedG: 255
        LedB: 255
        Ingredients:
          - Name: "Gin"
            Milliliters: 40
          - Name: "Tonic"
            Milliliters: 130
      - Id: "ginlemon"
        Name: "Gin Lemon"
        Subtitle: "Gin, Limone"
        Image: "ginlemon"
        Theme: "Teal"
        IsActive: false
        LedR: 50
        LedG: 255
        LedB: 0
        Ingredients:
          - Name: "Gin"
            Milliliters: 40
          - Name: "Limone"
            Milliliters: 130

  - Name: "Vodka Mode"
    Color: "#F7940A"
    LedColor: "CYAN"
    LiquidAssignments:
      - "Vodka"
      - "Tonic"
      - "Limone"
      - ""
    Cocktails:
      - Id: "vodkalemon"
        Name: "Vodka Lemon"
        Subtitle: "Vodka, Limone"
        Image: "vodkalemon"
        Theme: "Orange"
        IsActive: false
        LedR: 50
        LedG: 255
        LedB: 0
        Ingredients:
          - Name: "Vodka"
            Milliliters: 40
          - Name: "Limone"
            Milliliters: 130
      - Id: "vodkaredbull"
        Name: "Vodka Energy"
        Subtitle: "Vodka, Energy drink"
        Image: "vodkaredbull"
        Theme: "Orange"
        IsActive: false
        LedR: 30
        LedG: 255
        LedB: 0
        Ingredients:
          - Name: "Vodka"
            Milliliters: 40
          - Name: "Energy"
            Milliliters: 130
      - Id: "vodkatonic"
        Name: "Vodka Tonic"
        Subtitle: "Vodka, Tonica"
        Image: "vodkatonic"
        Theme: "Orange"
        IsActive: false
        LedR: 255
        LedG: 255
        LedB: 255
        Ingredients:
          - Name: "Vodka"
            Milliliters: 40
          - Name: "Tonic"
            Milliliters: 130

  - Name: "OG Mode"
    Color: "#F46036"
    LedColor: "RED"
    LiquidAssignments:
      - "Bitter rosso"
      - "Vermouth"
      - ""
      - "Gin"
    Cocktails:
      - Id: "negroni"
        Name: "Negroni"
        Subtitle: "Bitter rosso, Vermouth, Gin"
        Image: "negroni"
        Theme: "Burgundy"
        IsActive: true
        LedR: 0
        LedG: 255
        LedB: 0
        Ingredients:
          - Name: "Gin"
            Milliliters: 30
          - Name: "Bitter rosso"
            Milliliters: 30
          - Name: "Vermouth"
            Milliliters: 30
      - Id: "negronisbagliato"
        Name: "Negroni Sbagliato"
        Subtitle: "Bitter rosso, Vermouth, Prosecco"
        Image: "negronisbagliato"
        Theme: "Burgundy"
        IsActive: false
        LedR: 10
        LedG: 255
        LedB: 0
        Ingredients:
          - Name: "Bitter rosso"
            Milliliters: 30
          - Name: "Vermouth"
            Milliliters: 30
          - Name: "Prosecco"
            Milliliters: 60
      - Id: "americano"
        Name: "Americano"
        Subtitle: "Bitter rosso, Vermouth"
        Image: "americano"
        Theme: "Burgundy"
        IsActive: false
        LedR: 0
        LedG: 255
        LedB: 0
        Ingredients:
          - Name: "Bitter rosso"
            Milliliters: 30
          - Name: "Vermouth"
            Milliliters: 30
          - Name: "Tonic"
            Milliliters: 60
      - Id: "camparispritz"
        Name: "Spritz Rosso"
        Subtitle: "Bitter rosso, Prosecco"
        Image: "camparispritz"
        Theme: "Burgundy"
        IsActive: false
        LedR: 10
        LedG: 255
        LedB: 0
        Ingredients:
          - Name: "Bitter rosso"
            Milliliters: 40
          - Name: "Prosecco"
            Milliliters: 80
          - Name: "Tonic"
            Milliliters: 20
